name: cicd

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/cicd.yml'
      - 'sigexport/**'
      - '.dockerignore'
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  schedule:
    - cron:  '0 2 2 * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: addnab/docker-run-action@v3
        with:
          image: carderne/sigexport:latest
          options: -v ${{ github.workspace }}:/fresh
          run: |
            cd /fresh
            pip install . pytest pytest-cov
            pytest --cov sigexport

  docker-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag env var
        run: echo "TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: Docker Buildx base image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag "carderne/sigexport:$TAG" \
            --cache-from "carderne/sigexport" \
            --cache-to type=inline \
            .
