name: docker-build

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-build.yml'
      - 'sigexport/**'
      - '.dockerignore'
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  schedule:
    - cron:  '0 2 2 * *'
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag=carderne/sigexport:latest \
            --cache-from=carderne/sigexport:latest \
            --cache-to=type=inline \
            .
