name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: pipx run build --sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
